function [varargout] = loadsbxmat(anim, day, fov, varargin) 
%directory for  frame stimulus indices 
%loads a .mat file generated by Scanbox containing the frame/time onset and
%offset of stimuli
%load a "info" structure with fields corresponding to different parameters
%of the experiment

%info.evt.stim_on.frame and info.evt.stim_off.frame contains frame indices
%for stim on/off
%we will use this to index into the imaging file 

if length(varargin)==1 %if retinotopy experiment 
    exp=varargin{1}; 
    AnalDir= strcat('L:\Laura\ToAnalyze\', anim,'\', day, '\',exp,'\'); 
    if ~exist(AnalDir,'dir') 
         mkdir (AnalDir)
    end
    filename1=strcat(anim, '_', fov, '_', exp); 
    stim_info= load (fullfile (AnalDir, strcat(filename1, '.mat'))); %load any mat files, these would be the scanbox meta data
    varargout{1}= stim_info; 
    
elseif length(varargin)==2 %if gratings experiment 
    exp1=varargin{1};%contralateral eye first
    exp2=varargin{2}; %ipsilateral eye 

    AnalDir_contra= strcat('L:\Laura\ToAnalyze\', anim, '\',day, '\',exp1,'\');
     if ~exist(AnalDir_contra,'dir') 
             mkdir (AnalDir_contra)
     end
     filename2=strcat(anim, '_', fov, '_', exp1);
    stim_info_contra= load (fullfile (AnalDir_contra, strcat(filename2,'.mat'))); 

    AnalDir_ipsi= strcat('L:\Laura\ToAnalyze\', anim, '\',day, '\',exp2,'\'); 
     if ~exist(AnalDir_ipsi,'dir') 
             mkdir (AnalDir_ipsi)
     end
     filename3=strcat(anim, '_', fov, '_', exp2);
    stim_info_ipsi = load (fullfile (AnalDir_ipsi, strcat(filename3, '.mat')));
    varargout{1}= stim_info_contra; 
    varargout{2}= stim_info_ipsi; 
end


end